version: "2"
services:
  store_data:
    build: ./simple-store-data
    environment:
      VIRTUAL_DIRECTORY: ""
      VIRTUAL_PORT: 3000
      PORT: 3000
      # SECRET_KEY: ""
    network_mode: bridge
    restart: always
    mem_limit: 32M
